/**
  * DropboxLib
  *
  * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
  */

;(function (angular) {
	'use strict';

	angular.module('DropboxLib', ['angularMoment'])

	.run(function(Configuration) {
	    Configuration.oAuthClientId = 'q6b9rp7u1c9kgno';
	    Configuration.oAuthRedirectUri = 'http://localhost/Dropbox-AngularJS/callback.html';
	    Configuration.oAuthTokenUpdateCallback = function(token) {
	        // do something with refreshed token
	    }
	});

}(angular));