/**
  * DropboxLib
  *
  * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
  */

;(function (angular) {
'use strict';

angular.module('DropboxLib')
    .factory('Servers', [ServersModel]);

    function ServersModel() {
        return {
            //TODO: Write general description for this element
            MDEFAULT: 'default',
    
            //TODO: Write general description for this element
            AUTH: 'auth'
        };
    }

}(angular));
