/**
  * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
  */

(function () {
    function parseKeyValue(keyValue) {
        var obj = {};
        var key_value;
        var key;

        keyValue = (keyValue || '').split('&');

        keyValue.forEach(function (kv) {
            if (kv) {
                key_value = kv.split('=');
                key = decodeURIComponent(key_value[0]);
                obj[key] = (key_value[1]) ? decodeURIComponent(key_value[1]) : true;
            }
        });
        return obj;
    }

    function returnParams() {
        var queryString = window.location.hash.substring(1);
        var params = parseKeyValue(queryString);

        window.opener.postMessage(params, '*');
        window.close();
    }

    returnParams();

})();
