/**
 * DropboxLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
 */

;(function (angular) {
'use strict';

/**
 * Creates a instance of Account
 *
 * @constructor
 */
angular.module('DropboxLib')
    .factory('Account', ['BaseModel', AccountModel]);

    function AccountModel(BaseModel) {
        var Account = function (obj) {
            if (obj === undefined || obj === null) {
                return;
            }
            this.id = this.getValue(obj.id);
            this.name = this.getValue(obj.name);
            this.email = this.getValue(obj.email);
            this.createdAt = this.getValue(obj.createdAt);
            this.updatedAt = this.getValue(obj.updatedAt);
        };

        Account.prototype = new BaseModel();
        Account.prototype.constructor = Account;
    
        /**
         * Function containing information about the fields of this model
         * @return   {array}   Array of objects containing information about the fields
         */
        Account.prototype.mappingInfo = function() {
            return BaseModel.prototype.mappingInfo.call(this).concat([
                { name: 'id', realName: 'id' },
                { name: 'name', realName: 'name' },
                { name: 'email', realName: 'email' },
                { name: 'createdAt', realName: 'createdAt' },
                { name: 'updatedAt', realName: 'updatedAt' }
            ]);
        };
    
        /**
         * Function containing information about discriminator values
         * mapped with their corresponding model class names
         *
         * @return   {object}  Object containing Key-Value pairs mapping discriminator
         *                     values with their corresponding model classes
         */
        Account.prototype.discriminatorMap = function() {
            return {};
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {long}
         */
        Account.prototype.getId = function () {
            return this.id;
        };
    
        /**
         * Setter for Id
         * 
         * @param {long} value 
         */
        Account.prototype.setId = function (value) {
            this.id = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string}
         */
        Account.prototype.getName = function () {
            return this.name;
        };
    
        /**
         * Setter for Name
         * 
         * @param {string} value 
         */
        Account.prototype.setName = function (value) {
            this.name = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string}
         */
        Account.prototype.getEmail = function () {
            return this.email;
        };
    
        /**
         * Setter for Email
         * 
         * @param {string} value 
         */
        Account.prototype.setEmail = function (value) {
            this.email = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string}
         */
        Account.prototype.getCreatedAt = function () {
            return this.createdAt;
        };
    
        /**
         * Setter for CreatedAt
         * 
         * @param {string} value 
         */
        Account.prototype.setCreatedAt = function (value) {
            this.createdAt = value;
        };
    
        /**
         * TODO: Write general description for this method
         *
         * @return {string}
         */
        Account.prototype.getUpdatedAt = function () {
            return this.updatedAt;
        };
    
        /**
         * Setter for UpdatedAt
         * 
         * @param {string} value 
         */
        Account.prototype.setUpdatedAt = function (value) {
            this.updatedAt = value;
        };
    
        return Account;
    }

}(angular));
